development:
  server: "http://codingmart.com:9292/faye"
  secret_token: "secret"
test:
  server: "http://codingmart.com:9293/faye"
  #server: "http://localhost:9292/faye"
  secret_token: "secret"
production:
  server: "http://codingmart.com:9293/faye"
  secret_token: "7e1411d3acbfe735e33231055af005075e8cee19f40bf18e07e6475b39503534"
  signature_expiration: 3600 # one hour
